no_fits: 20
points_m: 10 # Actual points will be 2**points_m
model:
    type: 2 # 0: Voigt, 1: Lorentzian, 2: Pearson7
    components:
        v1_ :
            center : {min: 6910, max: 6920}
            amplitude: {min: 0.1, max: 800}
            sigma: {min: 0.1, max: 15}
            # gamma: {min: 0.1, max: 15}
            expon: {min: 1, max: 25}
        v2_ :
            center : {min: 6910, max: 6920}
            amplitude: {min: 0.1, max: 800}
            sigma: {min: 0.1, max: 15}
            # gamma: {min: 0.1, max: 15}
            expon: {min: 1, max: 25}
        v3_ :
            center : {min: 6922, max: 6935}
            amplitude: {min: 0.1, max: 800}
            sigma: {min: 0.1, max: 15}
            # gamma: {min: 0.1, max: 15}
            expon: {min: 1, max: 25}
        v4_ :
            center : {min: 6922, max: 6935}
            amplitude: {min: 0.1, max: 800}
            sigma: {min: 0.1, max: 15}
            # gamma: {min: 0.1, max: 15}
            expon: {min: 1, max: 25}
        # v5_ :
        #     center : {min: 6922, max: 6935}
        #     amplitude: {min: 0.1, max: 800}
        #     sigma: {min: 0.1, max: 15}
        #     gamma: {min: 0.1, max: 15}
            # expon: {min: 1, max: 25}
